### PR TITLE
Fixes #687 -Updated mtlx files to be W3C valid XML

### LINKED ISSUE #687: Some files in resources/Materials do not conform to W3C XML standards
Issues found:
1- Missing namespace declaration when using the XInclude syntax. The materialx node should contain the attribute `xmlns:xi="http://www.w3.org/2001/XInclude"`  whenever an xi:include tag is used.
2- XML comment happening before the `<?xml version="1.0"?>` tag, which must always be first.
3- Duplicate `<?xml version="1.0"?>` tags.
4- Broken tag saved as `<:anonymous name="1" />` .

### PR DESCRIPTION
**Pull request by JGamache-autodesk**

### CODE REVIEW

File: source/MaterialXFormat/File.cpp [hunk 1]
```diff
@@ -209,7 +209,22 @@ FilePathVec FilePath::getSubDirectories() const
...
+            FilePath newDir = *this / path;
+
+            if (d_type == DT_UNKNOWN)
+            {
+                if (newDir.isDirectory())
+                {
+                    d_type = DT_DIR;
+                }
+            }
+            if (d_type == DT_DIR)
```
Comment (JGamache-autodesk) [inline source/MaterialXFormat/File.cpp]: Was submitted in 94100edb. Got request to add braces around the "continue".

File: source/MaterialXFormat/XmlIo.cpp [hunk 2]
```diff
@@ -103,6 +105,9 @@ void elementToXml(ConstElementPtr elem, xml_node& xmlNode, const XmlWriteOptions
             {
                 if (!writtenSourceFiles.count(sourceUri))
                 {
+                    if (!xmlNode.attribute(XINCLUDE_NAMESPACE.c_str())) {
```
Comment (bernardkwok) [inline source/MaterialXFormat/XmlIo.cpp]: Trivial coding style. We've been putting "{" braces on separate lines.
