### PR TITLE
Fixed bug with CM on node inputs.

### LINKED ISSUE #413: CM transform node insert not breaking all connections properly in shader graph.
It seems when inserting a CM transform node the upstream output ports connection to the downstream input is not being broken properly. Need to break the input connection + the output connection to the input.
Added in unit test case to catch this.

### PR DESCRIPTION
**Pull request by niklasharrysson**
Fixes #413

### CODE REVIEW

File: source/MaterialXGenShader/ShaderGraph.cpp [hunk 1]
```diff
@@ -251,11 +251,14 @@ void ShaderGraph::addDefaultGeomNode(ShaderInput* input, const GeomPropDef& geom
 void ShaderGraph::addColorTransformNode(ShaderInput* input, const ColorSpaceTransform& transform, GenContext& context)
 {
     ColorManagementSystemPtr colorManagementSystem = context.getShaderGenerator().getColorManagementSystem();
-    if (!colorManagementSystem)
+    if (!colorManagementSystem || input->getConnection())
```
Comment (niklasharrysson) [inline source/MaterialXGenShader/ShaderGraph.cpp]: Add a check for input connections here, where all input connections have been created.

File: source/MaterialXGenShader/ShaderGraph.cpp [hunk 2]
```diff
@@ -1091,19 +1095,15 @@ void ShaderGraph::populateInputColorTransformMap(ColorManagementSystemPtr colorM
     const string& sourceColorSpace = input->getActiveColorSpace();
     if (shaderInput && !sourceColorSpace.empty())
     {
-        // Can skip inputs with connections as they are not legally allowed to have colorspaces specified.
-        if (!shaderInput->getConnection())
```
Comment (niklasharrysson) [inline source/MaterialXGenShader/ShaderGraph.cpp]: We can't check for input connections here, since we are in the middle of graph traversal and upstream connections have not been processed yet.
